### ISSUE TITLE
More features

### ISSUE THREAD

**Issue by rohitanil** [rohitanil/cowin-slot-tracker#4]
Filter by Age Limit
Vaccine Type

**Comment by UKnowWhoIm** [comment]
Next available date

**Comment by rohitanil** [comment]
@UKnowWhoIm maybe a Pincode-based search is more efficient and user friendly than district-based. From the top of my head, if we could get to the district_id from the user pincode, that makes it more user friendly. Guess the COWIN public API should have something but not anything straightforward.
Also in case multiple API hits are involved, its reasonable to have a lightweight database to cache the API responses and thereby reduce the API hits.

**Comment by UKnowWhoIm** [comment]
Yep caching results is a good idea especially if many people are using the API
