### ISSUE TITLE
Getting following error

### ISSUE THREAD

**Issue by raj007champ** [rohitanil/cowin-slot-tracker#7]
C:\Projects\cowin-slot-tracker>docker run -it --name covin-schedule --rm covin
': [Errno 2] No such file or directoryacker.py

**Comment by rohitanil** [comment]
@raj007champ is this the entire stack trace? If not, could you post the entire thing

**Comment by raj007champ** [comment]
C:\Projects\cowin-slot-tracker>docker build -t covin --rm .
[+] Building 11.5s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                                                          0.0s
 => => transferring dockerfile: 271B                                                                          0.0s
 => [internal] load .dockerignore                                                                             0.0s
 => => transferring context: 2B                                                                               0.0s
 => [internal] load metadata for docker.io/library/python:3.8-slim                                           11.2s
 => [internal] load build context                                                                             0.0s
 => => transferring context: 53.55kB                                                                          0.0s
 => [1/6] FROM docker.io/library/python:3.8-slim@sha256:2516c4bc037b8144b6104e73e6bdd0c861725d9ed7bd05095dde  0.0s
 => CACHED [2/6] RUN useradd --create-home --shell /bin/bash app_user                                         0.0s
 => CACHED [3/6] WORKDIR /home/app_user                                                                       0.0s
 => CACHED [4/6] COPY requirements.txt ./                                                                     0.0s
 => CACHED [5/6] RUN pip install --no-cache-dir -r requirements.txt                                           0.0s
 => [6/6] COPY . .                                                                                            0.0s
 => exporting to image                                                                                        0.0s
 => => exporting layers                                                                                       0.0s
 => => writing image sha256:6e386abdcccdf16d195d2e5d25a840b6cfc3a42e6341a3fe03fcc9b734450a02                  0.0s
 => => naming to docker.io/library/covin                                                                      0.0s

C:\Projects\cowin-slot-tracker>docker run -it --name covin-schedule --rm covin
': [Errno 2] No such file or directoryacker.py

C:\Projects\cowin-slot-tracker>docker run -it --name covin-schedule --rm covin
': [Errno 2] No such file or directoryacker.py

C:\Projects\cowin-slot-tracker>

**Comment by rohitanil** [comment]
Could you do an ls and see what all files you have in the directory. @raj007champ

**Comment by rohitanil** [comment]
@raj007champ not sure if you are using the latest code since there has been some updations made. Maybe try that also. Couldn't figure out the cause. @UKnowWhoIm could you please check this?

**Comment by rohitanil** [comment]
@UKnowWhoIm @raj007champ  couldn't reproduce this error.
