### ISSUE TITLE
[Errno 2] No such file or directoryacker.py

### ISSUE THREAD

**Issue by YuvrajRaghuvanshiS** [rohitanil/cowin-slot-tracker#9]
I am new to docker, this is what happening when I tried running it.

**Comment by YuvrajRaghuvanshiS** [comment]
![image](https://user-images.githubusercontent.com/52948878/117128148-a9400700-adba-11eb-91e0-fd5a7332190f.png)

**Comment by BharathBK** [comment]
Try removing `--rm` flag. Just use `docker build -t covin .`

**Comment by YuvrajRaghuvanshiS** [comment]
![image](https://user-images.githubusercontent.com/52948878/117142503-68052280-adcd-11eb-9e15-e14b980dc081.png)


No luck

**Comment by rohitanil** [comment]
Not really sure if this is a windows specific error, because it's working perfectly fine with mac and linux
